/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.GestorTareas;
import javax.swing.JOptionPane;

/**
 *
 * @author FernandoP, FrancisV, OdalisR, RichardCh
 */
public class Dashboard extends javax.swing.JFrame {
    private AgregarTarea agt = new AgregarTarea();
    private GestorTareas gt = new GestorTareas();
    TareasParaHoy thoy = new TareasParaHoy();
    private Integer tareash = 0;
    
    
   
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        if (gt.matriz_tareas != null){
            agt.crearArreglos();
            
            th();
        } else if (gt.matriz_tareas == null){
            System.out.println("ya se encuentra creado");
        }
        

     
    }
    private void th (){
        tareash = thoy.tareasEncontradas;
        
        tareasEncontradas.setText(tareash.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tareasEncontradas = new javax.swing.JLabel();
        tareasEncontradas1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnAgregarT = new javax.swing.JMenu();
        menuAgregarT = new javax.swing.JMenuItem();
        btnEditarT = new javax.swing.JMenu();
        menuEditarT = new javax.swing.JMenuItem();
        btnEditarT1 = new javax.swing.JMenu();
        menuEliminar = new javax.swing.JMenuItem();
        btnBuscarT = new javax.swing.JMenu();
        menubuscarT = new javax.swing.JMenuItem();
        menuTareasHoy = new javax.swing.JMenuItem();
        menuTareasP = new javax.swing.JMenuItem();
        menuTareasEP = new javax.swing.JMenuItem();
        menuTareasCompletadas = new javax.swing.JMenuItem();
        btnExit = new javax.swing.JMenu();
        menuCerrar = new javax.swing.JMenuItem();

        jMenu5.setText("Editar Tareas");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("Dashboard | Gestor de tareas UNL");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/bannerUnl1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/fondo tareas.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tareasEncontradas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tareasEncontradas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tareasEncontradas.setText("0");

        tareasEncontradas1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tareasEncontradas1.setText("Tareas Pendientes Para Hoy:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tareasEncontradas1)
                        .addGap(18, 18, 18)
                        .addComponent(tareasEncontradas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tareasEncontradas)
                    .addComponent(tareasEncontradas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        btnAgregarT.setText("Agregar Tarea");

        menuAgregarT.setText("Agregar Tarea");
        menuAgregarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarTActionPerformed(evt);
            }
        });
        btnAgregarT.add(menuAgregarT);

        jMenuBar1.add(btnAgregarT);

        btnEditarT.setText("Editar Tareas");

        menuEditarT.setText("Editar Tareas");
        menuEditarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarTActionPerformed(evt);
            }
        });
        btnEditarT.add(menuEditarT);

        jMenuBar1.add(btnEditarT);

        btnEditarT1.setText("Eliminar Tareas");

        menuEliminar.setText("Eliminar Tareas");
        menuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarActionPerformed(evt);
            }
        });
        btnEditarT1.add(menuEliminar);

        jMenuBar1.add(btnEditarT1);

        btnBuscarT.setText("Buscar Tareas");

        menubuscarT.setText("Buscar Tareas");
        menubuscarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubuscarTActionPerformed(evt);
            }
        });
        btnBuscarT.add(menubuscarT);

        menuTareasHoy.setText("Tareas para Hoy");
        menuTareasHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTareasHoyActionPerformed(evt);
            }
        });
        btnBuscarT.add(menuTareasHoy);

        menuTareasP.setText("Tareas Pendientes");
        menuTareasP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTareasPActionPerformed(evt);
            }
        });
        btnBuscarT.add(menuTareasP);

        menuTareasEP.setText("Tareas En Proceso");
        menuTareasEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTareasEPActionPerformed(evt);
            }
        });
        btnBuscarT.add(menuTareasEP);

        menuTareasCompletadas.setText("Tareas Completadas");
        menuTareasCompletadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTareasCompletadasActionPerformed(evt);
            }
        });
        btnBuscarT.add(menuTareasCompletadas);

        jMenuBar1.add(btnBuscarT);

        btnExit.setText("Cerrar Programa");

        menuCerrar.setText("Cerrar");
        menuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarActionPerformed(evt);
            }
        });
        btnExit.add(menuCerrar);

        jMenuBar1.add(btnExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAgregarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarTActionPerformed
        // TODO add your handling code here:
        AgregarTarea ag = new AgregarTarea();
        ag.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuAgregarTActionPerformed

    private void menubuscarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubuscarTActionPerformed
        // TODO add your handling code here:
        MostrarTareas mt = new MostrarTareas();
        mt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menubuscarTActionPerformed

    private void menuEditarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarTActionPerformed
        // TODO add your handling code here:
        EditarTareas et = new EditarTareas();
        et.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuEditarTActionPerformed

    private void menuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por Utilizar nuestro programa", "Ok", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_menuCerrarActionPerformed

    private void menuTareasPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTareasPActionPerformed
        // TODO add your handling code here:
        TareasPendientes tp = new TareasPendientes();
        tp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuTareasPActionPerformed

    private void menuTareasEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTareasEPActionPerformed
        // TODO add your handling code here:
        TareasEnProceso tep = new TareasEnProceso();
        tep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuTareasEPActionPerformed

    private void menuTareasCompletadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTareasCompletadasActionPerformed
        // TODO add your handling code here:
        TareasCompletadas tc = new TareasCompletadas();
        tc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuTareasCompletadasActionPerformed

    private void menuTareasHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTareasHoyActionPerformed
        // TODO add your handling code here:
        
        thoy.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuTareasHoyActionPerformed

    private void menuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarActionPerformed
        // TODO add your handling code here:
        EliminarTareas et = new EliminarTareas();
        et.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAgregarT;
    private javax.swing.JMenu btnBuscarT;
    private javax.swing.JMenu btnEditarT;
    private javax.swing.JMenu btnEditarT1;
    private javax.swing.JMenu btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem menuAgregarT;
    private javax.swing.JMenuItem menuCerrar;
    private javax.swing.JMenuItem menuEditarT;
    private javax.swing.JMenuItem menuEliminar;
    private javax.swing.JMenuItem menuTareasCompletadas;
    private javax.swing.JMenuItem menuTareasEP;
    private javax.swing.JMenuItem menuTareasHoy;
    private javax.swing.JMenuItem menuTareasP;
    private javax.swing.JMenuItem menubuscarT;
    private javax.swing.JLabel tareasEncontradas;
    private javax.swing.JLabel tareasEncontradas1;
    // End of variables declaration//GEN-END:variables
}
