/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.GestorTareas;
import java.util.Date;
import javax.swing.JOptionPane;
import vistas.modelo.MtableTareas;
import vistas.modelo.MtableTareasBuscar;

/**
 *
 * @author Odalis_R
 */
public class MostrarTareas extends javax.swing.JFrame {

    private GestorTareas gt = new GestorTareas();
    private AgregarTarea agt = new AgregarTarea();
    private MtableTareasBuscar modeloT = new MtableTareasBuscar();
    private MostrarTareas mt;
    private String[][] nuevaTablaBusqueda;

    public String[][] getNuevaTablaBusqueda() {
        return nuevaTablaBusqueda;
    }

    public void setNuevaTablaBusqueda(String[][] nuevaTablaBusqueda) {
        this.nuevaTablaBusqueda = nuevaTablaBusqueda;
    }

    /**
     * Creates new form MostrarTareas
     */
    public MostrarTareas() {
        initComponents();
        this.setLocationRelativeTo(null);
        gt.cargarDatos();
    }

    public void cargartabla() {

        modeloT.setMostrarT(mt);
        tbl_tablaT.setModel(modeloT);
        tbl_tablaT.updateUI();

    }

    private String dateAstring(Date fecha) {
        String fechabusqueda = "";

        fecha = lbl_fechaB.getDate();
        long d = fecha.getTime();
        java.sql.Date fechaD = new java.sql.Date(d);
        fechabusqueda = fechaD.toString();

        return fechabusqueda;
    }

    private void buscar(String busqueda) {
        
        int tareasEncontradas = 0;
        for (int cont = 0; cont < gt.matriz_tareas.length; cont++) {
            //System.out.println(gt.getMatriz_tareas()[cont][0]);
            //if (chbox_nTarea.isSelected() && busqueda.equalsIgnoreCase(gt.matriz_tareas[cont][0])) {
              if (gt.getMatriz_tareas()[cont][0] != null && chbox_nTarea.isSelected() && gt.matriz_tareas[cont][0].toLowerCase().startsWith(busqueda.toLowerCase())){
                tareasEncontradas++;
            } else if (gt.getMatriz_tareas()[cont][1] != null && chbox_materia.isSelected() && gt.matriz_tareas[cont][1].toLowerCase().startsWith(busqueda.toLowerCase())) {
                tareasEncontradas++;
            } else if (gt.getMatriz_tareas()[cont][2] != null && chbox_fecha.isSelected() && gt.matriz_tareas[cont][2].toLowerCase().startsWith(busqueda.toLowerCase())) {
                tareasEncontradas++;
            } else if (gt.getMatriz_tareas()[cont][4] != null && chbox_estado.isSelected() && gt.matriz_tareas[cont][4].toLowerCase().startsWith(busqueda.toLowerCase())) {
                tareasEncontradas++;
            }
        }

        if (tareasEncontradas == 0) {
            JOptionPane.showMessageDialog(null, "No se encontró ningún dato que coincida con la búsqueda", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        nuevaTablaBusqueda = new String[tareasEncontradas][gt.matriz_tareas[0].length];
        int indice = 0;
        for (int i = 0; i < gt.matriz_tareas.length; i++) {
            //if (chbox_nTarea.isSelected() && busqueda.equalsIgnoreCase(gt.matriz_tareas[i][0])) {
            if (gt.getMatriz_tareas()[i][0] != null && chbox_nTarea.isSelected() && gt.matriz_tareas[i][0].toLowerCase().startsWith(busqueda.toLowerCase())){
                nuevaTablaBusqueda[indice++] = gt.matriz_tareas[i];
            } else if (gt.getMatriz_tareas()[i][1] != null && chbox_materia.isSelected() && gt.matriz_tareas[i][1].toLowerCase().startsWith(busqueda.toLowerCase())) {
                nuevaTablaBusqueda[indice++] = gt.matriz_tareas[i];
            } else if (gt.getMatriz_tareas()[i][2] != null && chbox_fecha.isSelected() && gt.matriz_tareas[i][2].toLowerCase().startsWith(busqueda.toLowerCase())) {
                nuevaTablaBusqueda[indice++] = gt.matriz_tareas[i];
            } else if (gt.getMatriz_tareas()[i][4] != null && chbox_estado.isSelected() && gt.matriz_tareas[i][4].toLowerCase().startsWith(busqueda.toLowerCase())) {
                nuevaTablaBusqueda[indice++] = gt.matriz_tareas[i];
            }
        }

        modeloT.setMostrarT(this);
        tbl_tablaT.setModel(modeloT);
        tbl_tablaT.updateUI();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tablaT = new javax.swing.JTable();
        brn_regresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_buscar = new javax.swing.JTextField();
        lbl_fechaB = new com.toedter.calendar.JDateChooser();
        btn_buscar = new javax.swing.JButton();
        chbox_nTarea = new javax.swing.JCheckBox();
        chbox_materia = new javax.swing.JCheckBox();
        chbox_fecha = new javax.swing.JCheckBox();
        chbox_estado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbl_tablaT.setBackground(new java.awt.Color(255, 255, 255));
        tbl_tablaT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_tablaT);

        brn_regresar.setText("Regresar");
        brn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_regresarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/bannerUnl1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Ingresa el parámetro a buscar");

        lbl_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_buscarActionPerformed(evt);
            }
        });

        lbl_fechaB.setEnabled(false);

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        chbox_nTarea.setText("Nombre Tarea");
        chbox_nTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbox_nTareaActionPerformed(evt);
            }
        });

        chbox_materia.setText("Materia");
        chbox_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbox_materiaActionPerformed(evt);
            }
        });

        chbox_fecha.setText("Fecha");
        chbox_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbox_fechaActionPerformed(evt);
            }
        });

        chbox_estado.setText("Estado");
        chbox_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbox_estadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(lbl_fechaB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(chbox_nTarea)
                        .addGap(18, 18, 18)
                        .addComponent(chbox_materia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbox_fecha)
                        .addGap(18, 18, 18)
                        .addComponent(chbox_estado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_fechaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar)
                    .addComponent(chbox_nTarea)
                    .addComponent(chbox_materia)
                    .addComponent(chbox_fecha)
                    .addComponent(chbox_estado))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(brn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(brn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_regresarActionPerformed
        // TODO add your handling code here:
        Dashboard db = new Dashboard();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_brn_regresarActionPerformed

    private void chbox_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbox_materiaActionPerformed
        // TODO add your handling code here:
        if (chbox_materia.isSelected()) {
            chbox_nTarea.setEnabled(false);
            chbox_fecha.setEnabled(false);
            chbox_estado.setEnabled(false);

        } else {
            chbox_nTarea.setEnabled(true);
            chbox_fecha.setEnabled(true);
            chbox_estado.setEnabled(true);
        }
    }//GEN-LAST:event_chbox_materiaActionPerformed

    private void chbox_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbox_fechaActionPerformed
        // TODO add your handling code here:
        if (chbox_fecha.isSelected()) {
            chbox_materia.setEnabled(false);
            chbox_nTarea.setEnabled(false);
            chbox_estado.setEnabled(false);
            lbl_fechaB.setEnabled(true);
            lbl_buscar.setEnabled(false);

        } else {
            chbox_materia.setEnabled(true);
            chbox_nTarea.setEnabled(true);
            chbox_estado.setEnabled(true);
            lbl_fechaB.setEnabled(false);
            lbl_buscar.setEnabled(true);
        }
    }//GEN-LAST:event_chbox_fechaActionPerformed

    private void chbox_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbox_estadoActionPerformed
        // TODO add your handling code here:
        if (chbox_estado.isSelected()) {
            chbox_materia.setEnabled(false);
            chbox_fecha.setEnabled(false);
            chbox_nTarea.setEnabled(false);

        } else {
            chbox_materia.setEnabled(true);
            chbox_fecha.setEnabled(true);
            chbox_nTarea.setEnabled(true);
        }
    }//GEN-LAST:event_chbox_estadoActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        if (lbl_buscar.isEnabled()) {
            buscar(lbl_buscar.getText());

        } else if (lbl_fechaB.isEnabled()) {
            buscar(dateAstring(lbl_fechaB.getDate()));
        }

        lbl_buscar.setText("");
        chbox_materia.setEnabled(true);
        chbox_fecha.setEnabled(true);
        chbox_nTarea.setEnabled(true);
        chbox_estado.setEnabled(true);
        chbox_nTarea.setSelected(false);
        chbox_materia.setSelected(false);
        chbox_fecha.setSelected(false);
        chbox_estado.setSelected(false);
        lbl_buscar.setEnabled(true);
        lbl_fechaB.setEnabled(false);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void chbox_nTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbox_nTareaActionPerformed
        // TODO add your handling code here:
        if (chbox_nTarea.isSelected()) {
            chbox_materia.setEnabled(false);
            chbox_fecha.setEnabled(false);
            chbox_estado.setEnabled(false);

        } else {
            chbox_materia.setEnabled(true);
            chbox_fecha.setEnabled(true);
            chbox_estado.setEnabled(true);
        }
    }//GEN-LAST:event_chbox_nTareaActionPerformed

    private void lbl_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarTareas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brn_regresar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JCheckBox chbox_estado;
    private javax.swing.JCheckBox chbox_fecha;
    private javax.swing.JCheckBox chbox_materia;
    private javax.swing.JCheckBox chbox_nTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lbl_buscar;
    private com.toedter.calendar.JDateChooser lbl_fechaB;
    private javax.swing.JTable tbl_tablaT;
    // End of variables declaration//GEN-END:variables
}
